name:
description:
meta_description:
aboutPage: true
paginate: 20
baseurl: /
domain_name: 'http://wramalho.github.io'
disqus: false
disqus_shortname: 'your-disqus-shortname'
repository: wramalho/wramalho.github.io

# Details for the RSS feed generator
url:            'wramalho.github.io'
author:         'Waldo A. Ramalho'
authorTwitter:  'waldoramalho'
authorGithub: 'wramalho'

permalink:       /:year/:title/

defaults:
    -
        scope:
            path: "" # empty string for all files
            type: pages
        values:
            layout: default
    -
        scope:
            path: "" # empty string for all files
            type: posts
        values:
            layout: post
    -
        scope:
            path: ""
            type: drafts
        values:
            layout: post
